mysite/employee/urls.py
from django.urls import path
from . import views

app_name = "employee"

urlpatterns = [
    path('', views.DepartmentList.as_view(), name = 'all'),
    path('department/create/', views.CreateDepartment.as_view(), name = 'create_department'),
    path('department/edit/<int:pk>', views.EditDepartment.as_view(), name = 'edit_department'),
    path('department/delete/<int:pk>', views.DeleteDepartment.as_view(), name = 'delete_department')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROUTE = os.path.join(BASE_DIR, "site")

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r'^site/(?P<path>.*)$',serve,
            {'document_route':SITE_ROUTE, "show_indexes":True}, name="site_path"
            ),
    path("", TemplateView.as_view(template_name='home/main.html')),
    path("school/", include("school.urls")),
    path("employee/", include("employee.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

mysite/employee/models.py
from django.db import models
from django.conf import settings

# Create your models here.

# Department 
class Department(models.Model):
    DEPARTMENT_CHOICES = {
        ('HS', 'Home Science'),
        ('PA', 'Painting'),
        ('ENG', 'English'),
        ('DEO', 'Data Entry Operations'),
        ('BC', 'Basic Computing')
    }
    name = models.CharField(choices = DEPARTMENT_CHOICES, max_length=50)
    location = models.CharField(max_length=50)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_name_display()} - {self.location}"

# Employee
class Employee(models.Model):
    name = models.CharField(max_length=255)
    job = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete = models.CASCADE, null=False)

    def __str__(self):
        return f"{self.name}"

mysite/school/models.py
from django.db import models

# Create your models here.

# School
class School(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=20)
    yearOfEstablishment = models.PositiveIntegerField()
    email = models.EmailField(max_length=200) 
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
# Student
class Student(models.Model):
    name = models.CharField(max_length=200)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete = models.CASCADE, null=False)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

mysite/employee/forms.py
from django.forms import ModelForm
from employee.models import Department

class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        # fields = "__all__"
        fields = ['name', 'location']
        

mysite/employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Department
from employee.forms import DepartmentForm
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# Department List View
class DepartmentList(View):
    template = 'employee/department_list.html'

    def get(self, request):
        department_list = Department.objects.all()
        context = {
            'department_list':department_list
        }
        return render(request, self.template, context)
   
# Create Department View
class CreateDepartment(LoginRequiredMixin, View):
    template = 'employee/department_form.html'
    success_url = 'employee:all'

    def get(self, request):
        form = DepartmentForm()
        context = {
            'form':form
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = DepartmentForm(request.POST)
        if not form.is_valid():
            context = {
                'form':form
            }
            return render(request, self.template, context)
        
        obj = form.save(commit = False)
        obj.owner = self.request.user
        obj.save()

        messages.success(request, "Department was successfully created.")
        return redirect(self.success_url)

# Edit Department View 
class EditDepartment(LoginRequiredMixin, View):
    model = Department
    template = "employee/department_form.html"
    success_url = "employee:all"
    
    def get(self, request, pk):
        department = get_object_or_404(self.model, id=pk)
        form = DepartmentForm(instance=department)
        context = {
            'form':form
        }
        return render(request, self.template, context)
    
    def post(self, request, pk):
        department = get_object_or_404(self.model, id=pk)
        form = DepartmentForm(request.POST,instance=department)
        if not form.is_valid():
            context = {
                'form':form
            }
            messages.error(request, "Please enter all the required details.")
            return render(request, self.template, context)
        
        obj = form.save(commit = False)

        if obj.owner == self.request.user:
            obj.save()
            messages.success(request, "Department was successfully updated.")
        else:
            messages.error(request, "You are not allowed to edit.")
            
        return redirect(self.success_url)
    
# Delete Department View
class DeleteDepartment(LoginRequiredMixin, View):
    model = Department
    template = "employee/department_confirm_delete.html"
    success_url = "employee:all"

    def get(self, request, pk):
        department = get_object_or_404(self.model, id=pk)
        context = {
            "department":department
        }
        return render(request, self.template, context)
    
    def post(self, request, pk):
        department = get_object_or_404(self.model, id=pk)
        department.delete()
        messages.info(request, "Department was successfully deleted.")
        return redirect(self.success_url)

mysite/employee/templates/employee/department_confirm_delete.html
{% extends "base_master.html" %}
{% block title %}
    Department Confirm Delete
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Delete Department</h1>
        <h3>Are you sure you want to delete this {{department.get_name_display}}?</h3>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete">
            <button class="btn btn-warning" type="submit" 
            onclick="window.location = '{% url 'employee:all' %}';return false;">Cancel</button>
        </form>
    </div>
{% endblock content %}

mysite/employee/templates/employee/department_form.html
{% extends "base_master.html" %}
{% block title %}
    Department Form
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Department Form</h1>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <input class="btn btn-primary" type="submit" value="Submit">
            <button class="btn btn-danger" type="submit" 
            onclick="window.location = '{% url 'employee:all' %}';return false;">Cancel</button>
        </form>
    </div>
{% endblock content %}

mysite/employee/templates/employee/department_list.html
{% extends "base_master.html" %}
{% block title %}
    Department List
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Department Details</h1>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary" 
        onclick="window.location = '{% url 'employee:create_department' %}'">
        <i class="bi bi-plus-square"></i> Add Department
        </button>
        {% endif %}
          
        {% if department_list %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Department Name</th>
                    <th scope="col">Department Location</th>
                    <th scope="col">
                    {% if user.is_authenticated %}
                        Actions
                    {% endif %}
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for department in department_list %}
                <tr>
                    <th scope="row">{{department.id}}</th>
                    <td>{{department.get_name_display}}</td>
                    <td>{{department.location}}</td>
                    <td>
                        {% if user.is_authenticated %}

                            {% if department.owner == user %}
                                <button type="button" class="btn btn-sm btn-primary"
                                onclick="window.location = '{% url 'employee:edit_department' department.id %}'">
                                <i class="bi bi-pencil"></i> Edit
                                </button>
                                <button type="button" class="btn btn-sm btn-danger"
                                onclick="window.location = '{% url 'employee:delete_department' department.id %}'">
                                <i class="bi bi-trash"></i> Delete
                                </button>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger"> Access Denied</i> 
                            {% endif %}

                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <div class="alert alert-info" role="alert">
                There are no departments in the database.
            </div>
        {% endif %}
    </div>
{% endblock content %}