mysite/employee/urls.py
from django.urls import path
from . import views

app_name = "employee"

urlpatterns = [
    path('', views.DepartmentList.as_view(), name = 'all'),
    path('department/create/', views.CreateDepartment.as_view(), name = 'create_department'),
    path('department/edit/<int:pk>', views.EditDepartment.as_view(), name = 'edit_department'),
    path('department/delete/<int:pk>', views.DeleteDepartment.as_view(), name = 'delete_department')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROUTE = os.path.join(BASE_DIR, "site")

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r'^site/(?P<path>.*)$',serve,
            {'document_route':SITE_ROUTE, "show_indexes":True}, name="site_path"
            ),
    path("", TemplateView.as_view(template_name='home/main.html')),
    path("school/", include("school.urls")),
    path("employee/", include("employee.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

mysite/school/urls.py
from django.urls import path
from . import views

app_name = "school"

urlpatterns = [
    path('', views.SchoolList.as_view(), name = "all"),
    path('create', views.SchoolCreate.as_view(), name = "school_create"),
    path('detail/<int:pk>', views.SchoolDetail.as_view(), name = "school_detail"),
    path('update/<int:pk>', views.SchoolUpdate.as_view(), name = "school_update"),
    path('delete/<int:pk>', views.SchoolDelete.as_view(), name = "school_delete"),
    path('student', views.StudentList.as_view(), name = "student_list"),
    path('student/create', views.StudentCreate.as_view(), name = "student_create"),
    path('student/detail/<int:pk>', views.StudentDetail.as_view(), name = "student_detail"),
    path('student/update/<int:pk>', views.StudentUpdate.as_view(), name = "student_update"),
    path('student/delete/<int:pk>', views.StudentDelete.as_view(), name = "student_delete")
]

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/home/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

mysite/home/templates/home/main.html
{% extends "base_master.html" %}
{% block title %}
    Django Sample
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Django Samples</h1>
        {% if user.is_authenticated %}
            <h3 class="text-secondary">Welcome {{user.get_username}}</h3>
        {% else %}
            <h3 class="text-secondary">Welcome Guest</h3>
        {% endif %}
        <div class="list-group">
            <a href="{% url 'school:all' %}" class="list-group-item list-group-item-action" aria-current="true">
                Schools
            </a>
            <a href="{% url 'employee:all' %}" class="list-group-item list-group-item-action" aria-current="true">
                Employees
            </a>
        </div>
    </div>
{% endblock content %}