mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import TemplateView
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROUTE = os.path.join(BASE_DIR, "site")

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r'^site/(?P<path>.*)$',serve,
            {'document_route':SITE_ROUTE, "show_indexes":True}, name="site_path"
            ),
    path("", TemplateView.as_view(template_name='home/main.html')),
    path("school/", include("school.urls")),
    path("employee/", include("employee.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

mysite/school/urls.py
from django.urls import path
from . import views

app_name = "school"

urlpatterns = [
    path('', views.SchoolList.as_view(), name = "all"),
    path('create', views.SchoolCreate.as_view(), name = "school_create"),
    path('detail/<int:pk>', views.SchoolDetail.as_view(), name = "school_detail"),
    path('update/<int:pk>', views.SchoolUpdate.as_view(), name = "school_update"),
    path('delete/<int:pk>', views.SchoolDelete.as_view(), name = "school_delete"),
    path('student', views.StudentList.as_view(), name = "student_list"),
    path('student/create', views.StudentCreate.as_view(), name = "student_create"),
    path('student/detail/<int:pk>', views.StudentDetail.as_view(), name = "student_detail"),
    path('student/update/<int:pk>', views.StudentUpdate.as_view(), name = "student_update"),
    path('student/delete/<int:pk>', views.StudentDelete.as_view(), name = "student_delete")
]

mysite/school/models.py
from django.db import models

# Create your models here.

# School
class School(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=20)
    yearOfEstablishment = models.PositiveIntegerField()
    email = models.EmailField(max_length=200) 
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
# Student
class Student(models.Model):
    name = models.CharField(max_length=200)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete = models.CASCADE, null=False)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

mysite/school/forms.py
from django.forms import ModelForm
from school.models import School, Student

# School Form
class SchoolForm(ModelForm):
    class Meta:
        model = School
        fields = "__all__"

# Student Form
class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

mysite/school/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from school.models import School, Student
from school.forms import SchoolForm, StudentForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# School list view
class SchoolList(View):
    template = 'school/school_list.html'

    def get(self, request):
        school_list = School.objects.all()
        context = {
            'school_list':school_list
        }
        return render(request, self.template, context)
    
# School Create View
class SchoolCreate(LoginRequiredMixin, View):
    template = "school/school_form.html"
    success_url = "school:all"

    def get(self, request):
        form = SchoolForm()
        context = {
            'form':form
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = SchoolForm(request.POST)
        if not form.is_valid():
            context = {
                'form':form
            }
            return render(request, self.template, context)
        form.save()
        return redirect(self.success_url)

# School Details View
class SchoolDetail(View):
    model = School
    template = 'school/school_detail.html'

    def get(self, request, pk):
        school = get_object_or_404(self.model, id=pk)
        context = {
            'school':school
        }
        return render(request, self.template, context)
    
# School Update View
class SchoolUpdate(LoginRequiredMixin, View):
    model = School
    template = 'school/school_form.html'
    success_url = "school:all"

    def get(self, request, pk):
        school = get_object_or_404(self.model, id=pk)
        form = SchoolForm(instance=school)
        context = {
            'form':form
        }
        return render(request, self.template, context)
    
    def post(self, request, pk):
        school = get_object_or_404(self.model, id=pk)
        form = SchoolForm(request.POST,instance=school)
        if not form.is_valid():
            context = {
                'form':form
            }
            return render(request, self.template, context)
        form.save()
        return redirect(self.success_url)

# School Delete View
class SchoolDelete(LoginRequiredMixin, View):
    model = School
    template = 'school/school_confirm_delete.html'
    success_url = "school:all"

    def get(self, request, pk):
        school = get_object_or_404(self.model, id=pk)
        context = {
            'school':school
        }
        return render(request, self.template, context)
    
    def post(self, pk):
        school = get_object_or_404(self.model, id=pk)
        school.delete()
        return redirect(self.success_url)

# Students List View
class StudentList(View):
    template = "school/student_list.html"

    def get(self, request):
        student_list = Student.objects.all()
        context = {
            'student_list':student_list
        }
        return render(request, self.template, context)

# Student Create View
class StudentCreate(LoginRequiredMixin, View):
    template = "school/student_form.html"
    success_url = "school:student_list"

    def get(self, request):
        form = StudentForm()
        context = {
            'form':form
        }
        return render(request, self.template, context)
    def post(self, request):
        form = StudentForm(request.POST)
        if not form.is_valid():
            context = {
                "form":form
            }
            return render(request, self.template, context)
        form.save()
        return redirect(self.success_url)
    
# Student Detail View
class StudentDetail(View):
    model = Student
    template = "school/student_detail.html"

    def get(self, request, pk):
        student = get_object_or_404(self.model, id=pk)
        context = {
            'student':student
        }
        return render(request, self.template, context)
    
# Student Update View
class StudentUpdate(LoginRequiredMixin,View):
    model = Student
    template = "school/student_form.html"
    success_url = "school:student_list"

    def get(self, request, pk):
        student = get_object_or_404(self.model, id=pk)
        form = StudentForm(instance=student)
        context = {
            'form':form
        }
        return render(request, self.template, context)
    
    def post(self, request, pk):
        student = get_object_or_404(self.model, id=pk)
        form = StudentForm(request.POST,instance=student)
        if not form.is_valid():
            context = {
                'form':form
            }
            return render(request, self.template, context)
        form.save()
        return redirect(self.success_url)

# Student Delete View  
class StudentDelete(LoginRequiredMixin,View):
    model = Student
    template = "school/student_confirm_delete.html"
    success_url = "school:student_list"

    def get(self, request, pk):
        student = get_object_or_404(self.model, id=pk)
        context = {
            'student':student
        }
        return render(request, self.template, context)
    def post(self, request, pk):
        student = get_object_or_404(self.model, id=pk)
        student.delete()
        return redirect(self.success_url)

mysite/school/templates/school/school_confirm_delete.html
{% extends "base_master.html" %}
{% block title %}
    School Confirm Delete
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Delete School</h1>
        <h3>Are you sure you want to delete this {{school.name}}?</h3>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete">
            <button class="btn btn-warning" type="submit" 
        onclick="window.location = '{% url 'school:school_detail' school.id %}';return false;">Cancel</button>
        </form>
    </div>
{% endblock content %}

mysite/school/templates/school/school_detail.html
{% extends "base_master.html" %}
{% block title %}
    School Details
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>{{school.name}}</h1>
        <p>City - {{school.city}}</p>
        <p>Country - {{school.country}}</p>
        <p>Year of Establishment - {{school.yearOfEstablishment}}</p>
        <p>Email - {{school.email}}</p>
        <p>Phone - {{school.phone}}</p>
        <button class="btn btn-success" type="submit" 
        onclick="window.location = '{% url 'school:all' %}'">Back</button>
        {% if user.is_authenticated %}
            <button class="btn btn-warning" type="submit" 
            onclick="window.location = '{% url 'school:school_update' school.id %}'">Update</button>
            <button class="btn btn-danger" type="submit" 
            onclick="window.location = '{% url 'school:school_delete' school.id %}'">Delete</button>
        {% endif %}
    </div>
{% endblock content %}

mysite/school/templates/school/school_form.html
{% extends "base_master.html" %}

{% block title %}
    School Form
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>School Form</h1>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <input class="btn btn-success" type="submit" value="Submit">
            <button class="btn btn-warning" type="submit"
            onclick="window.location = '{% url 'school:all' %}';return false;">Cancel</button>
        </form>
    </div>    
{% endblock content %}

mysite/school/templates/school/school_list.html
{% extends "base_master.html" %}
{% block title %}
    Schools
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Schools</h1>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary" 
            onclick="window.location = '{% url 'school:school_create' %}'">Add School</button>
        {% endif %}
        <button type="button" class="btn btn-primary"
        onclick="window.location = '{% url 'school:student_list' %}'">View Students</button>
    </div>
    <div class="container">
        {% if school_list  %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name of the School</th>
                        <th scope="col">Location</th>
                        <th scope="col">
                        {% if user.is_authenticated %}
                            Actions
                        {% endif %}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for school in school_list %}
                        <tr>
                            <th scope="row">{{school.id}}</th>
                            <td>{{school.name}}</td>
                            <td>{{school.city}}, {{school.country}}.</td>
                            <td>
                                <button type="button" class="btn btn-success btn-sm" 
                                onclick="window.location = '{% url 'school:school_detail' school.id %}'">View</button>
                                {% if user.is_authenticated %}
                                    <button type="button" class="btn btn-warning btn-sm"
                                    onclick="window.location = '{% url 'school:school_update' school.id %}'">Update</button>
                                    <button type="button" class="btn btn-danger btn-sm"
                                    onclick="window.location = '{% url 'school:school_delete' school.id %}'">Delete</button>
                                {% endif %}
                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info" role="alert">
               There are no schools in the database.
            </div>
        {% endif %}
    </div>
{% endblock content %}

mysite/school/templates/school/student_confirm_delete.html
{% extends "base_master.html" %}
{% block title %}
    Student Confirm Delete
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Delete Student</h1>
        <h3>Are you sure you want to delete this {{student.name}}?</h3>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete">
            <button class="btn btn-warning" type="submit"
        onclick="window.location = '{% url 'school:student_detail' student.id %}';return false;">Cancel</button>
        </form>
    </div>
{% endblock content %}

mysite/school/templates/school/student_detail.html
{% extends "base_master.html" %}
{% block title %}
    student detail
{% endblock title %}  
{% block content %}
    <div class="container mt-3">
        <h1>{{student.name}}</h1>
        <p>Age - {{student.age}}</p>
        <p>School - {{student.school}}</p>
        <p>Email - {{student.email}}</p>
        <p>Phone - {{student.phone}}</p>
        <button class="btn btn-success" type="submit"
        onclick="window.location = '{% url 'school:student_list' %}'">Back</button>
        {% if user.is_authenticated %}
            <button class="btn btn-warning" type="submit"
            onclick="window.location = '{% url 'school:student_update' student.id %}'">Update</button>
            <button class="btn btn-danger" type="submit"
            onclick="window.location = '{% url 'school:student_delete' student.id %}'">Delete</button>
        {% endif %}
        
    </div>
{% endblock content %}  

mysite/school/templates/school/student_form.html
{% extends "base_master.html" %}

{% block title %}
    student form
{% endblock title %}

{% block content %}
    <div class="container mt-3">
        <h1>Student Form</h1>
        <form class="m-3" action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <input class="btn btn-primary" type="submit" value="Submit">
            <button class="btn btn-danger" type="submit" 
            onclick="window.location = '{% url 'school:student_list' %}';return false;">Cancel</button>
        </form>
    </div>
{% endblock content %}

mysite/school/templates/school/student_list.html
{% extends "base_master.html" %}
{% block title %}
    Students
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Students</h1>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary"
            onclick="window.location = '{% url 'school:student_create' %}'">Add Student</button>
        {% endif %}
        
        <button type="button" class="btn btn-primary"
        onclick="window.location = '{% url 'school:all' %}'">View Schools</button>
    </div>
    <div class="container mt-4">
        {% if student_list %}
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name of the Student</th>
                    <th scope="col">School</th>
                    <th scope="col">
                    {% if user.is_authenticated %}
                        Actions
                    {% endif %}
                    </th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in student_list %}
                        <tr>
                            <th scope="row">{{student.id}}</th>
                            <td>{{student.name}}</td>
                            <td>{{student.school}}</td>
                            <td>
                                <button type="button" class="btn btn-success btn-sm"
                                onclick="window.location = '{% url 'school:student_detail' student.id %}'">View</button>
                                {% if user.is_authenticated %}
                                    <button type="button" class="btn btn-warning btn-sm"
                                    onclick="window.location = '{% url 'school:student_update' student.id %}'">Update</button>
                                    <button type="button" class="btn btn-danger btn-sm" 
                                    onclick="window.location = '{% url 'school:student_delete' student.id %}'">Delete</button>
                                {% endif %}
                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table> 
        {% else %}
            <div class="alert alert-info" role="alert">
               There are no students in the database.
            </div>
        {% endif %}    
    </div>
{% endblock content %}